name: Deployment to Development Environment

on:
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build:dev && node ftp.js
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USER_NAME: ${{ secrets.FTP_USER_NAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_REMOTE_FOLDER: ${{ secrets.FTP_REMOTE_FOLDER }}
        CONTEXT: branch-deploy
        HEAD: develop
